# Generated by Django 4.0.6 on 2022-07-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_calendar_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_method',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL',
                                   max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
